name: Deploy to Development

on:
  push:
    branches:
      - develop
  workflow_dispatch:

concurrency:
  group: deploy-development
  cancel-in-progress: false

env:
  NODE_VERSION: '20'
  PNPM_VERSION: '9'

jobs:
  deploy:
    name: Deploy to Development Environment
    runs-on: ubuntu-latest
    timeout-minutes: 20
    environment:
      name: development
      url: https://dev.yourapp.com
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup pnpm
        uses: pnpm/action-setup@v3
        with:
          version: ${{ env.PNPM_VERSION }}

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Build application
        run: pnpm --filter web build
        env:
          NODE_ENV: production
          NEXT_PUBLIC_ENVIRONMENT: development

      - name: Deploy to Development
        run: |
          echo "Deploying to development environment..."
          # Add your deployment commands here
          # Examples:
          # - Vercel: vercel --prod --token=${{ secrets.VERCEL_TOKEN }}
          # - Netlify: netlify deploy --prod
          # - Custom: scp/rsync to server
          # - Docker: docker push and update
          echo "Deployment completed!"
        env:
          DEPLOY_TOKEN: ${{ secrets.DEPLOY_TOKEN }}

  e2e-tests:
    name: Run E2E Tests
    runs-on: ubuntu-latest
    needs: deploy
    timeout-minutes: 30
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup pnpm
        uses: pnpm/action-setup@v3
        with:
          version: ${{ env.PNPM_VERSION }}

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Install Playwright browsers
        run: pnpm exec playwright install --with-deps

      - name: Run E2E tests
        run: pnpm --filter e2e test
        env:
          BASE_URL: https://dev.yourapp.com
          CI: true

      - name: Upload test results
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: e2e-test-results-development
          path: apps/e2e/test-results/
          retention-days: 7

      - name: Upload test report
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: e2e-test-report-development
          path: apps/e2e/playwright-report/
          retention-days: 7

  notify:
    name: Notify Deployment Status
    runs-on: ubuntu-latest
    needs: [deploy, e2e-tests]
    if: always()
    
    steps:
      - name: Send notification
        run: |
          if [[ "${{ needs.deploy.result }}" == "success" ]] && [[ "${{ needs.e2e-tests.result }}" == "success" ]]; then
            echo "✅ Development deployment successful!"
            # Add notification service here (Slack, Discord, etc.)
          else
            echo "❌ Development deployment failed!"
            # Add notification service here
          fi

