name: Deploy to Development

on:
  push:
    branches:
      - develop

jobs:
  deploy:
    name: Deploy to Development
    runs-on: ubuntu-latest
    timeout-minutes: 20
    environment:
      name: development
      url: https://dev.example.com

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 10.19.0

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Build application
        run: pnpm --filter web build
        env:
          NEXT_PUBLIC_SITE_URL: https://dev.example.com
          NEXT_PUBLIC_PRODUCT_NAME: "Your SaaS (Dev)"
          NEXT_PUBLIC_SITE_TITLE: "Your SaaS - Development"
          NEXT_PUBLIC_SITE_DESCRIPTION: "Your SaaS Development Environment"
          NODE_ENV: production

      - name: Deploy to Development
        run: |
          echo "🚀 Deploying to Development environment..."
          echo "Branch: develop"
          echo "Environment: development"
          # Add your deployment commands here
          # Examples:
          # - Vercel: vercel deploy --prod --token=${{ secrets.VERCEL_TOKEN }}
          # - AWS: aws s3 sync ./out s3://your-bucket
          # - Docker: docker push your-image:dev
          echo "✅ Deployment completed!"

      - name: Deployment Summary
        run: |
          echo "📦 Deployment Details:"
          echo "  - Environment: Development"
          echo "  - Branch: develop"
          echo "  - Commit: ${{ github.sha }}"
          echo "  - Author: ${{ github.actor }}"
